# Generated by Django 3.2 on 2021-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='external_article',
            field=models.CharField(max_length=256),
        ),
    ]
